channels:
- conda-forge
dependencies:
- python=3.10.18
- pip<=25.1.1
- pip:
  - mlflow==3.1.1
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - psutil==6.1.0
  - scikit-learn==1.4.2
  - scipy==1.12.0
name: mlflow-env
